### ISSUE TITLE
two-column view: end-of-line hidden under line numbers of RHS col

### ISSUE THREAD

**Issue by srenatus** [sminez/ad#44]
### Describe the bug

- When there are two windows open, and 
- the left window has a long line,
- and I go to the end of that line,
- then the cursor is highlighting a part of the numbers column of the right window, and
- the text at the end of that long line is hidden.

### Screenshots

This is the scenario, with a long line 12 of the LHS window:

<img width="1248" alt="Screenshot 2024-10-28 at 10 08 56" src="https://github.com/user-attachments/assets/7f0a5ead-f698-45c0-9f7c-c8e396c7fca5">

then I go to the very right of that line and see this:

<img width="1246" alt="Screenshot 2024-10-28 at 10 09 06" src="https://github.com/user-attachments/assets/c1be7d86-a4c8-451a-9104-db000ada6157">

The focus is still on the LHS window, it just seems to be "beneath" the number col of the RHS window.

### Versions & OS Details

- OS: macos
- [9c96e2a](https://github.com/sminez/ad/commit/9c96e2a4bd3ba883db300c2e63c31cabc5aaa006)

### Additional context

Congratulations on landing the UI overhaul 🎈

**Comment by sminez** [comment]
Ah, yeah the behaviour of horizontal scrolling seems pretty wonky at the moment. I hadn't noticed it previously because I only ever had a single fullscreen `ad` window when using it, but using splits makes it really obvious.

In addition to addressing this particular issue I probably need to take a look at the horizontal scrolling behaviour in general.

**Comment by srenatus** [comment]
Perhaps related: When I save, the theme color stops a bit too early in the status line:

<img width="1255" alt="image" src="https://github.com/user-attachments/assets/869007ff-56e5-46d7-88ae-a06d5b356b8f">
<img width="1249" alt="Screenshot 2024-10-28 at 11 13 06" src="https://github.com/user-attachments/assets/954746af-3f60-4a20-8ff5-cb3bf38a2cb7">

when the messages goes away, it's again colored as expected:

<img width="1251" alt="image" src="https://github.com/user-attachments/assets/d31e8bd6-4a75-494c-9eec-0ed7dbbdb980">

**Comment by sminez** [comment]
oh weird! Not sure that's related actually... could you raise a separate issue for that one?

**Comment by sminez** [comment]
This one turned out to be pretty simple (and daft): I had pretty much the same logic for handling horizontal and vertical scrolling but the horizontal case wasn't accounting for the presence of the number/sign column... :sweat_smile: 

So that's the scrolling and cursor position issue sorted out but please be aware that scrolling to the right can (and will) mess up syntax highlighting as you move past the start of constructs as the tokenizer currently works per-line (already not good) and only on the text that is actively visible (really not good). Sorting this out is covered in #5 but it's not a super high priority at the moment as getting it right will likely involve some reworking on the rendering logic and I have some other improvements I'd like to make there first.

**Comment by srenatus** [comment]
Thanks! ❤️ 

I don't care much about syntax highlighting, so I'm fine with that. Thanks again 😃
